### PR TITLE
Added Advanced BBCode Box 

### PR DESCRIPTION
**Pull request by egrapa**
Hopefully getting it right this time.
Note the README file is different in first commit but corrected in 4th. (Not sure how to delete an intermediate commit....). You can accept both or refuse both.

This pull request adds VSE directory in ext.

From: https://www.phpbb.com/customise/db/extension/advanced_bbcode_box/
Version: 3.1.1

### CODE REVIEW

**Comment by egrapa** [comment]
--- comments removed ---  will add German in a different Branch

**Comment by egrapa** [comment]
README.md is now back to original with this latest update.

**Comment by emk** [comment]
**TODO list**

Before we can merge this, we need to do the following:
- [ ] Remove all the changes to the `README.md` file.
- [ ] Add version numbers and URLs to the commit messages for each extension and language pack.
- [ ] Get rid of the `.DS_Store` files.
- [ ] Put the Advanced BBCode extension on a different branch from the language packs, so that we can test it and deploy it separately.

There are two ways we can do this:
1. I'm pretty good at git "history editing", so please feel free to just send me the version numbers and URLs for each extension and language pack, and I'll clean everything up. I can probably find the necessary time this weekend.
2. Alteratively, if you want, you could create new branches named `advanced-bbcode` and `language-packs`, and redo the imports. I'll fix `.gitignore` in the main repository so that it ignores `.DS_Store`.

Yes, this process is always a bit awkward the first time through. But it will go much faster in the future!

Thank you once again for these great patches! I hope to merge the language packs right away, and I'm looking to testing out Advanced BBCode and seeing what cool things it can do. :-)

**Comment by egrapa** [comment]
I've reverted the README.md file and will do the version and URLs now

**Comment by emk** [comment]
Let me know if I can unstick you on any git stuff, by the way. I have a few minutes available today.

**Comment by egrapa** [comment]
Removed German Language pack from this branch.

**Comment by emk** [comment]
Good morning! I merged your three language packs manually, and deployed them to the site. Thank you very much!

As for the BBCode extension, let's find some time to re-import that on a brand-new branch, and then merge it normally. To begin, please see [these new instructions on how to make local branches based off `custom`](https://github.com/language-learners/phpbb#how-to-prepare-a-pull-request).

You may also need to wipe out the existing changes on your local `custom` branch by running something like the following commands:

``` sh
git remote add upstream git@github.com:language-learners/phpbb.git
git fetch upstream
git checkout custom
# WARNING! This will lose local changes!
git reset --hard upstream/custom
```

If you do that, you should probably be able to adapt the same commands from the new pull-request instructions.

Once again, thank you for helping maintain the site!

**Comment by egrapa** [comment]
Great, that is clear!

**Pull request closed without merging**
